title: Ethos AT
description: Audio transcriber program powered by AI
show_downloads: false
#google_analytics: G-F1ZJEV5JDL
#theme: jekyll-theme-primer # Para rodar no GitHub Pages
remote_theme: pages-themes/primer # Para rodar local
#include:
#  - assets/css


plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-seo-tag

# Desativa o carregamento autom√°tico de metadados do GitHub
github: {}



# Available themes:
# jekyll-theme-cayman
# jekyll-theme-minimal
# jekyll-theme-slate - Interessante
# jekyll-theme-time-machine
# jekyll-theme-merlot
# jekyll-theme-architect
# jekyll-theme-dinky
# jekyll-theme-hacker - Interessante
# jekyll-theme-leap-day
# jekyll-theme-midnight - Interessante
# jekyll-theme-modernist
# jekyll-theme-tactile - Interessante